bot:
  bot-token:
  username:
  usedLanguages:
    - uz-UZ
    - ru-RU
jowi:
  api-key:
  api-secret:
  api-url-v010:
  api-url-v3:
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:../data/demo
    username: sa
    driver-class-name: org.h2.Driver
    password: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
