bot:
  bot-token: ${BOT_TOKEN}
  username: "blueBankz_bot"
  usedLanguages:
    - uz-UZ
    - ru-RU
jowi:
  api-key: ${JOWI_API_KEY}
  api-secret: ${JOWI_API_SECRET}
  api-url-v010: "https://api.jowi.club/v010"
  api-url-v3: "https://api.jowi.club/v3"
payment:
  click-token: ${CLICK_PROVIDER_TOKEN}
  payme-token: ${PAYME_PROVIDER_TOKEN}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:../data/demo
    username: sa
    driver-class-name: org.h2.Driver
    password: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
